### ISSUE TITLE
Bring changes to the PPU

### ISSUE THREAD

**Issue by neauoire** [max22-/uxn-esp32#1]
The Screen device has a recent change, where the pixel/sprite drawing modes each have their own ports.

https://git.sr.ht/~rabbits/uxn/tree/master/item/src/uxnemu.c#L307

![image](https://user-images.githubusercontent.com/1455726/128638746-1ccfa953-aeef-421e-8b76-b38aab120785.png)

**Comment by max22-** [comment]
Done ;)
